import { flyAppDetails } from "./flyAppDetails.generated.js";

const flyImagePaths = {
  "blue-winged-olive": "/fly-images/blue-winged-olive.jpg",
  "parachute-adams": "/fly-images/parachute-adams.jpg",
  "elk-hair-caddis": "/fly-images/elk-hair-caddis.jpg",
  "griffiths-gnat": "/fly-images/griffiths-gnat.jpg",
  "x-caddis": "/fly-images/x-caddis.jpg",
  stimulator: "/fly-images/stimulator.jpg",
  "zebra-midge": "/fly-images/zebra-midge.png",
  "pheasant-tail-nymph": "/fly-images/pheasant-tail-nymph.jpg",
  "hares-ear-nymph": "/fly-images/hares-ear-nymph.jpg",
  "prince-nymph": "/fly-images/prince-nymph.jpg",
  "copper-john": "/fly-images/copper-john.jpg",
  "woolly-bugger": "/fly-images/woolly-bugger.jpg",
  "clouser-minnow": "/fly-images/clouser-minnow.jpg",
  "muddler-minnow": "/fly-images/muddler-minnow.jpg",
  zonker: "/fly-images/zonker.jpg",
  sculpzilla: "/fly-images/sculpzilla.jpg",
  rs2: "/fly-images/rs2.jpg",
  "sparkle-dun": "/fly-images/sparkle-dun.png",
  "wd-40": "/fly-images/wd-40.png",
  "soft-hackle-pheasant-tail": "/fly-images/soft-hackle-pheasant-tail.png",
  "barrs-emerger": "/fly-images/barrs-emerger.png",
  "chubby-chernobyl": "/fly-images/chubby-chernobyl.png",
  "foam-ant": "/fly-images/foam-ant.png",
  beetle: "/fly-images/beetle.png",
  "daves-hopper": "/fly-images/daves-hopper.png",
  "partridge-and-orange": "/fly-images/partridge-and-orange.png",
  "soft-hackle-hares-ear": "/fly-images/soft-hackle-hares-ear.png",
  "leadwing-coachman": "/fly-images/leadwing-coachman.png",
  "march-brown-wet": "/fly-images/march-brown-wet.png",
  perdigon: "/fly-images/perdigon.jpg",
  frenchie: "/fly-images/frenchie.jpg",
  "walts-worm": "/fly-images/walts-worm.png",
  "rainbow-warrior": "/fly-images/rainbow-warrior.png",
};

export const flyLibrary = [
  {
    slug: "blue-winged-olive",
    name: "Blue Winged Olive",
    categorySlug: "dry-flies",
    difficulty: "Beginner",
    sizeRange: "#16-24",
    summary: "A slim mayfly dry that gives trout boxes a reliable small-profile surface option.",
    whyItMatters: "It gives the library a clean mayfly anchor that stays easy to trust and easy to organize.",
    whenToUse: "Use it when trout are feeding near the surface and a smaller mayfly look belongs in the mix.",
    tags: ["dry", "trout", "mayfly", "baetis", "beginner", "classic", "box-essential", "year-round"],
    materials: [
      ["Hook", "Dai-Riki 305, #16-24"],
      ["Thread", "Olive 6/0 or 140D"],
      ["Wing", "Two natural CDC feathers"],
      ["Hackle", "Dun dry-fly hackle"],
    ],
    image: "/app-assets/blue-winged-olive.jpg",
  },
  {
    slug: "parachute-adams",
    name: "Parachute Adams",
    categorySlug: "dry-flies",
    difficulty: "Beginner",
    sizeRange: "#10-20",
    summary: "A visible attractor dry that remains one of the easiest all-around trout patterns to keep in a box.",
    whyItMatters: "It is a benchmark confidence fly that helps anglers cover a lot of water without overthinking the surface game.",
    whenToUse: "Use it when you want a dependable dry that feels broad, visible, and easy to fish with confidence.",
    tags: ["dry", "trout", "mayfly", "attractor", "beginner", "classic", "versatile", "box-essential", "year-round"],
    steps: [
      "Start the thread just behind the eye and tie in the wing-post material at the front of the hook.",
      "Wrap tightly around the base of the post so it stands straight, narrow, and stable.",
      "Tie in the tail and dub a slim gray body below the post.",
      "Wrap the hackle parachute-style and finish below the post.",
    ],
  },
  {
    slug: "elk-hair-caddis",
    name: "Elk Hair Caddis",
    categorySlug: "dry-flies",
    difficulty: "Beginner",
    sizeRange: "#12-16",
    summary: "A practical caddis dry that stays visible, buoyant, and easy to keep in rotation.",
    whyItMatters: "It gives the box a simple caddis anchor that still feels useful across a wide range of trout water.",
    whenToUse: "Use it when caddis are in the conversation or when you want a visible, fishable dry that is easy to read.",
    tags: ["dry", "trout", "caddis", "classic", "beginner", "box-essential", "versatile", "small-stream", "year-round"],
    materials: [
      ["Hook", "TMC 100 or Daiichi 1180"],
      ["Thread", "Brown or olive 6/0-8/0"],
      ["Body", "Tan or olive superfine dubbing"],
      ["Wing", "Natural elk hair"],
    ],
    image: "/app-assets/elk-hair-caddis.jpg",
  },
  {
    slug: "griffiths-gnat",
    name: "Griffith's Gnat",
    categorySlug: "dry-flies",
    difficulty: "Intermediate",
    sizeRange: "#16-22",
    summary: "A classic midge dry that keeps small-surface coverage in the box.",
    whyItMatters: "It stops the dry-fly row from becoming only mayflies and caddis.",
    whenToUse: "Use it when trout are tuned to smaller food near the surface.",
    tags: ["dry", "trout", "midge", "classic", "technical-water", "year-round"],
  },
  {
    slug: "x-caddis",
    name: "X-Caddis",
    categorySlug: "dry-flies",
    difficulty: "Intermediate",
    sizeRange: "#14-18",
    summary: "A lower-profile caddis pattern for anglers who want a quieter adult look.",
    whyItMatters: "It gives the caddis group a more restrained option than a bigger float-heavy dry.",
    whenToUse: "Use it when trout are close to the film and a subtler caddis shape makes sense.",
    tags: ["dry", "trout", "caddis", "technical-water", "summer"],
  },
  {
    slug: "stimulator",
    name: "Stimulator",
    categorySlug: "dry-flies",
    difficulty: "Intermediate",
    sizeRange: "#8-16",
    summary: "A larger attractor dry that brings visibility and a stronger footprint to the surface.",
    whyItMatters: "It gives anglers an easy-to-see dry when smaller patterns feel too quiet.",
    whenToUse: "Use it in faster water, western-style dry-fly fishing, or whenever visibility matters.",
    tags: ["dry", "trout", "attractor", "western", "small-stream", "summer"],
  },
  {
    slug: "zebra-midge",
    name: "Zebra Midge",
    categorySlug: "nymphs",
    difficulty: "Beginner",
    sizeRange: "#16-22",
    summary: "A slim midge nymph that stays useful because it is simple, compact, and easy to trust.",
    whyItMatters: "It is one of the clearest everyday examples of a small nymph earning permanent box space.",
    whenToUse: "Use it when smaller subsurface food is part of the day or when you want a clean technical nymph row.",
    tags: ["nymph", "trout", "midge", "beginner", "versatile", "box-essential", "year-round"],
  },
  {
    slug: "pheasant-tail-nymph",
    name: "Pheasant Tail Nymph",
    categorySlug: "nymphs",
    difficulty: "Beginner",
    sizeRange: "#12-20",
    summary: "A classic mayfly nymph that belongs in almost every organized trout library.",
    whyItMatters: "It teaches category logic while still covering real day-to-day trout fishing.",
    whenToUse: "Use it when you want a dependable mayfly-leaning nymph that never feels out of place.",
    tags: ["nymph", "trout", "mayfly", "classic", "beginner", "versatile", "box-essential", "year-round"],
  },
  {
    slug: "hares-ear-nymph",
    name: "Hare's Ear Nymph",
    categorySlug: "nymphs",
    difficulty: "Beginner",
    sizeRange: "#12-18",
    summary: "An all-purpose searching nymph that keeps the trout box broad without becoming confusing.",
    whyItMatters: "It pairs well with slimmer nymphs and helps cover general searching situations cleanly.",
    whenToUse: "Use it when you want a nymph with broad utility and classic box value.",
    tags: ["nymph", "trout", "classic", "beginner", "versatile", "box-essential", "year-round"],
  },
  {
    slug: "prince-nymph",
    name: "Prince Nymph",
    categorySlug: "nymphs",
    difficulty: "Intermediate",
    sizeRange: "#10-16",
    summary: "A more visible nymph that adds contrast and searching value to the subsurface row.",
    whyItMatters: "It gives the nymph box a recognizable pattern with more presence than tiny technical flies.",
    whenToUse: "Use it when you want a nymph with a stronger silhouette and a more assertive searching role.",
    tags: ["nymph", "trout", "classic", "attractor", "western", "box-essential"],
  },
  {
    slug: "copper-john",
    name: "Copper John",
    categorySlug: "nymphs",
    difficulty: "Intermediate",
    sizeRange: "#12-18",
    summary: "An attractor-style nymph that adds a bolder subsurface option to the lineup.",
    whyItMatters: "It balances softer classics with a more assertive fly that is still easy to understand.",
    whenToUse: "Use it when you want a nymph with more presence than a slim technical pattern.",
    tags: ["nymph", "trout", "attractor", "versatile", "western", "year-round"],
  },
  {
    slug: "woolly-bugger",
    name: "Woolly Bugger",
    categorySlug: "streamers",
    difficulty: "Beginner",
    sizeRange: "#4-10",
    summary: "A classic streamer that covers a huge amount of practical fishing with very little extra explanation.",
    whyItMatters: "Few flies are as useful for both beginner tying and long-term fly-box value.",
    whenToUse: "Use it when you want a first-stop streamer that can prospect and cover water almost anywhere.",
    tags: ["streamer", "trout", "classic", "beginner", "versatile", "box-essential", "year-round"],
  },
  {
    slug: "clouser-minnow",
    name: "Clouser Minnow",
    categorySlug: "streamers",
    difficulty: "Beginner",
    sizeRange: "#2-8",
    summary: "A streamlined baitfish-style pattern with broad searching utility.",
    whyItMatters: "It gives the streamer category a simple, modern classic shape that feels useful across more than one fishery.",
    whenToUse: "Use it when you want a cleaner baitfish profile and a straightforward streamer decision.",
    tags: ["streamer", "trout", "baitfish", "classic", "beginner", "versatile", "box-essential"],
  },
  {
    slug: "muddler-minnow",
    name: "Muddler Minnow",
    categorySlug: "streamers",
    difficulty: "Intermediate",
    sizeRange: "#4-10",
    summary: "A classic streamer that keeps a stronger silhouette and more traditional look in the row.",
    whyItMatters: "It broadens streamer coverage beyond only bugger and baitfish logic.",
    whenToUse: "Use it when you want a traditional streamer profile with enough presence to stand apart.",
    tags: ["streamer", "trout", "classic", "small-stream", "western"],
  },
  {
    slug: "zonker",
    name: "Zonker",
    categorySlug: "streamers",
    difficulty: "Intermediate",
    sizeRange: "#4-8",
    summary: "A movement-forward streamer that adds animation and variety to the box.",
    whyItMatters: "It gives the streamer row an obvious motion-based contrast to tighter classic shapes.",
    whenToUse: "Use it when you want more movement and a more animated streamer profile.",
    tags: ["streamer", "trout", "versatile", "year-round"],
  },
  {
    slug: "sculpzilla",
    name: "Sculpzilla",
    categorySlug: "streamers",
    difficulty: "Intermediate",
    sizeRange: "#4-8",
    summary: "A sculpin-style streamer that adds a stronger bottom-oriented profile.",
    whyItMatters: "It gives trout boxes a bigger-meal option without making the whole streamer row bulky.",
    whenToUse: "Use it when a sculpin-leaning streamer belongs in the plan.",
    tags: ["streamer", "trout", "western", "big-fish"],
  },
  {
    slug: "rs2",
    name: "RS2",
    categorySlug: "emergers",
    difficulty: "Intermediate",
    sizeRange: "#18-24",
    summary: "A small transition-zone pattern that bridges nymph and emerger logic.",
    whyItMatters: "It gives technical trout boxes a proven answer when fish are keyed on smaller food near the film.",
    whenToUse: "Use it when trout are focused on tiny insects and you want a fly that can live between categories.",
    tags: ["emerger", "nymph", "trout", "midge", "mayfly", "classic", "technical-water", "year-round"],
  },
  {
    slug: "sparkle-dun",
    name: "Sparkle Dun",
    categorySlug: "emergers",
    difficulty: "Intermediate",
    sizeRange: "#14-20",
    summary: "A mayfly emerger that keeps film-focused trout coverage organized.",
    whyItMatters: "It helps anglers stay in the feeding window when fish are close to the surface but not fully on dries.",
    whenToUse: "Use it during mayfly activity when a transition pattern feels more honest than a high-floating adult.",
    tags: ["emerger", "trout", "mayfly", "technical-water", "box-essential"],
  },
  {
    slug: "wd-40",
    name: "WD-40",
    categorySlug: "emergers",
    difficulty: "Intermediate",
    sizeRange: "#18-24",
    summary: "A slim emerger for smaller insects and more selective trout situations.",
    whyItMatters: "It gives the emerger row a clean technical option for midge and small mayfly coverage.",
    whenToUse: "Use it when trout are feeding on small insects near the film and restraint matters.",
    tags: ["emerger", "trout", "midge", "mayfly", "technical-water", "year-round"],
  },
  {
    slug: "soft-hackle-pheasant-tail",
    name: "Soft Hackle Pheasant Tail",
    categorySlug: "emergers",
    difficulty: "Intermediate",
    sizeRange: "#14-18",
    summary: "A crossover fly that links emerger usefulness with soft-hackle movement.",
    whyItMatters: "It connects two important categories and adds movement without losing a mayfly identity.",
    whenToUse: "Use it when you want a film-oriented fly with a little more life than a static emerger.",
    tags: ["emerger", "wet-fly", "soft-hackle", "trout", "mayfly", "classic"],
  },
  {
    slug: "barrs-emerger",
    name: "Barr's Emerger",
    categorySlug: "emergers",
    difficulty: "Intermediate",
    sizeRange: "#16-20",
    summary: "A practical emerger that keeps hatch-stage coverage easier to organize.",
    whyItMatters: "It gives the emerger category a dedicated, dependable pattern instead of forcing that job onto unrelated flies.",
    whenToUse: "Use it when trout are focused on insects moving into the film.",
    tags: ["emerger", "trout", "mayfly", "technical-water"],
  },
  {
    slug: "chubby-chernobyl",
    name: "Chubby Chernobyl",
    categorySlug: "terrestrials",
    difficulty: "Beginner",
    sizeRange: "#6-14",
    summary: "A high-floating terrestrial and attractor that keeps summer boxes visible and simple.",
    whyItMatters: "It gives anglers a confidence fly that is easy to see and easy to organize around.",
    whenToUse: "Use it when you want a visible terrestrial with broad summer utility.",
    tags: ["terrestrial", "dry", "trout", "attractor", "beginner", "western", "box-essential", "summer", "small-stream"],
  },
  {
    slug: "foam-ant",
    name: "Foam Ant",
    categorySlug: "terrestrials",
    difficulty: "Beginner",
    sizeRange: "#12-18",
    summary: "A compact terrestrial that covers one of the most practical summer food sources.",
    whyItMatters: "It gives the terrestrial row a simple, durable, easy-to-fish pattern.",
    whenToUse: "Use it when you want a straightforward terrestrial for small streams and summer trout water.",
    tags: ["terrestrial", "dry", "trout", "beginner", "small-stream", "summer", "box-essential"],
  },
  {
    slug: "beetle",
    name: "Beetle",
    categorySlug: "terrestrials",
    difficulty: "Beginner",
    sizeRange: "#10-16",
    summary: "A simple terrestrial that rounds out the box with a broad, easy-to-fish silhouette.",
    whyItMatters: "It complements hoppers and ants without making the category harder to manage.",
    whenToUse: "Use it when you want a visible, approachable terrestrial that covers a lot of bank-oriented water.",
    tags: ["terrestrial", "dry", "trout", "beginner", "summer", "small-stream"],
  },
  {
    slug: "daves-hopper",
    name: "Dave's Hopper",
    categorySlug: "terrestrials",
    difficulty: "Intermediate",
    sizeRange: "#8-12",
    summary: "A classic hopper that gives the terrestrial row more seasonal depth.",
    whyItMatters: "It keeps traditional hopper logic visible inside a modern organized box.",
    whenToUse: "Use it during hopper season when you want a classic western-style terrestrial.",
    tags: ["terrestrial", "dry", "trout", "classic", "western", "summer", "box-essential"],
  },
  {
    slug: "partridge-and-orange",
    name: "Partridge and Orange",
    categorySlug: "wet-flies",
    difficulty: "Beginner",
    sizeRange: "#12-18",
    summary: "A classic soft hackle that proves useful wet flies do not need much clutter.",
    whyItMatters: "It gives the wet-fly category a foundational pattern that is simple, elegant, and easy to revisit.",
    whenToUse: "Use it when you want a soft-hackle benchmark that keeps the category grounded.",
    tags: ["wet-fly", "soft-hackle", "trout", "classic", "beginner", "easiest", "box-essential"],
  },
  {
    slug: "soft-hackle-hares-ear",
    name: "Soft Hackle Hare's Ear",
    categorySlug: "wet-flies",
    difficulty: "Beginner",
    sizeRange: "#12-16",
    summary: "A soft-hackle wet that brings classic movement into a familiar nymph-adjacent shape.",
    whyItMatters: "It helps wet-fly anglers keep one foot in classic movement and one in practical all-around trout use.",
    whenToUse: "Use it when you want a subtle moving wet that still feels familiar and approachable.",
    tags: ["wet-fly", "soft-hackle", "trout", "classic", "beginner", "versatile", "year-round"],
  },
  {
    slug: "leadwing-coachman",
    name: "Leadwing Coachman",
    categorySlug: "wet-flies",
    difficulty: "Intermediate",
    sizeRange: "#8-14",
    summary: "A traditional winged wet that adds historical depth and a distinct classic silhouette.",
    whyItMatters: "It broadens wet-fly knowledge beyond only soft hackles and keeps classic pattern literacy visible.",
    whenToUse: "Use it when you want a more traditional wet in the box or in the knowledge hub.",
    tags: ["wet-fly", "trout", "classic", "swing", "year-round"],
  },
  {
    slug: "march-brown-wet",
    name: "March Brown Wet",
    categorySlug: "wet-flies",
    difficulty: "Intermediate",
    sizeRange: "#10-14",
    summary: "A classic wet-fly pattern that gives the category another recognized traditional anchor.",
    whyItMatters: "It helps the wet-fly section feel like a real family of patterns instead of a single-note archive.",
    whenToUse: "Use it when you want another traditional wet-fly reference with a classic trout identity.",
    tags: ["wet-fly", "trout", "classic", "mayfly"],
  },
  {
    slug: "perdigon",
    name: "Perdigon",
    categorySlug: "euro-nymphs",
    difficulty: "Intermediate",
    sizeRange: "#14-18",
    summary: "A streamlined euro nymph built around speed, efficiency, and clean tactical purpose.",
    whyItMatters: "It is one of the clearest modern examples of euro box discipline and repeatable organization.",
    whenToUse: "Use it when you want a slim tactical fly in a direct-contact subsurface workflow.",
    tags: ["euro", "nymph", "trout", "versatile", "box-essential", "year-round"],
  },
  {
    slug: "frenchie",
    name: "Frenchie",
    categorySlug: "euro-nymphs",
    difficulty: "Beginner",
    sizeRange: "#14-18",
    summary: "A straightforward euro standard that makes tactical nymphing more approachable.",
    whyItMatters: "It gives anglers a familiar, repeatable euro fly that feels easy to keep in rotation.",
    whenToUse: "Use it when you want a simple euro pattern with broad everyday utility.",
    tags: ["euro", "nymph", "trout", "beginner", "box-essential", "versatile", "year-round"],
  },
  {
    slug: "walts-worm",
    name: "Walt's Worm",
    categorySlug: "euro-nymphs",
    difficulty: "Beginner",
    sizeRange: "#12-16",
    summary: "A simple euro-friendly pattern that proves useful tactical flies do not need complexity.",
    whyItMatters: "It reinforces the value of simple, repeatable flies inside a disciplined euro row.",
    whenToUse: "Use it when you want an approachable euro nymph that stays easy to tie and easy to organize.",
    tags: ["euro", "nymph", "trout", "beginner", "easiest", "versatile", "year-round"],
  },
  {
    slug: "rainbow-warrior",
    name: "Rainbow Warrior",
    categorySlug: "euro-nymphs",
    difficulty: "Intermediate",
    sizeRange: "#14-18",
    summary: "An attractor-leaning euro pattern that adds brightness and contrast to the tactical row.",
    whyItMatters: "It keeps euro boxes from becoming too one-note while still fitting a clean tactical system.",
    whenToUse: "Use it when you want a euro fly with more visual separation from neutral patterns.",
    tags: ["euro", "nymph", "trout", "attractor", "midge", "year-round"],
  },
].map((fly) => ({
  ...fly,
  appDetail: flyAppDetails[fly.slug] || null,
  image: flyImagePaths[fly.slug] || fly.image,
}));
